### ISSUE TITLE
[Tools/IA] Test doc templates to see if they build

### ISSUE THREAD

**Issue by DonNateR** [rackerlabs/docs-repo-template#23]
Use the content templates found in this directory with their make files to see if the templates build correctly and see if the templates format correctly. The following are the directories which include templates that need to be tested:

- [ ] [api-guide-template](https://github.com/rackerlabs/docs-repo-template/tree/master/api-guide-template)

- [ ] [user-guide](https://github.com/rackerlabs/docs-repo-template/tree/master/user-guide)

**Comment by robb-romans** [comment]
Moved to https://github.rackspace.com/IX/docs-starter-kit/issues/3
