### ISSUE TITLE
(IA) Review comments for User Guide template

### ISSUE THREAD

**Issue by lauracly** [rackerlabs/docs-repo-template#25]
Laura's review comments for the UG template:

Overall very good job; feel like this is a great start and contains the building blocks for a complete UG. There are a few organizational things that I think can be moved around, and also providing examples will be very helpful.

1. Index file - I think the API section/chapter should come last since its a reference information type. Admin and other things should come before that.
2. Overview - Recommended reorganization is to have A: System Requirements/Architecture B: Compatibility C: Features/Comp
3. Deployment/Planning - at some point in here, mention that what they are installing should document only the MVP (minimal viable product). Many times teams will try to document all options, and that is not the intention here.
4. Getting Started - Recommended reorganization have Config first (since it mentions having the product in a stable state), and then Access and then Nav.
5. Using - the user tasks/use cases should match/reflect the items listed in the features in the overview. Make sure to map those out and that everything is accounted for (except for pure admin things).
6. API - match the dev guides for the content and make sure the full guides reside on Developer; we shouldn't reinvent the wheel here.
7. Logging/Monitoring - don't have links to these existing "elsewhere". Everything should be in these guides.
8. Support - should be the overall title, with a Troubleshooting subsection.

Overall, don't encourage teams to have content all over the place. If they are going to create a UG, it should be complete. Logging, monitoring, etc shouldn't stay in random places, and APIs should be on developer. We should try to encourage consistency, not enable it.

**Comment by robb-romans** [comment]
Replaced by https://github.rackspace.com/IX/docs-starter-kit/issues/1
